export const totalFollowers = "23 004";

export const platformsData = [
  {
    id: "facebook",
    platform: "facebook",
    user: "@nathanf",
    total: "1 987",
    unit: "Followers",
    today: 12,
    isPositive: true,
    borderColor: "border-facebook",
  },
  {
    id: "twitter",
    platform: "twitter",
    user: "@nathanf",
    total: "1 044",
    unit: "Followers",
    today: 99,
    isPositive: false,
    borderColor: "border-twitter",
  },
  {
    id: "instagram",
    platform: "instagram",
    user: "@realnathanf",
    total: "11k",
    rawTotal: "11 283",
    unit: "Followers",
    today: 1099,
    isPositive: true,
    borderColor: "bg-instagram",
  },
  {
    id: "youtube",
    platform: "youtube",
    user: "Nathan F.",
    total: "8 239",
    unit: "Subscribers",
    today: 144,
    isPositive: false,
    borderColor: "border-youtube",
  },
];

export const todayStats = [
  {
    id: 1,
    platform: "facebook",
    title: "Page views",
    value: "87",
    percentage: 3,
    isPositive: true,
  },
  {
    id: 2,
    platform: "facebook",
    title: "Likes",
    value: "52",
    percentage: 2,
    isPositive: false,
  },
  {
    id: 3,
    platform: "instagram",
    title: "Likes",
    value: "5 462",
    percentage: 2257,
    isPositive: true,
  },
  {
    id: 4,
    platform: "instagram",
    title: "Profile views",
    value: "52k",
    rawValue: "52 366",
    percentage: 1375,
    isPositive: true,
  },
  {
    id: 5,
    platform: "twitter",
    title: "Retweets",
    value: "117",
    percentage: 303,
    isPositive: true,
  },
  {
    id: 6,
    platform: "twitter",
    title: "Likes",
    value: "507",
    percentage: 553,
    isPositive: true,
  },
  {
    id: 7,
    platform: "youtube",
    title: "Likes",
    value: "107",
    percentage: 19,
    isPositive: false,
  },
  {
    id: 8,
    platform: "youtube",
    title: "Total views",
    value: "1 407",
    percentage: 12,
    isPositive: false,
  },
];

export default {
  totalFollowers,
  platformsData,
  todayStats,
};
